# Generated by Django 2.2.7 on 2019-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8192)),
                ('url', models.CharField(max_length=8192, unique=True)),
                ('created', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='posts_post_created_26d9b3_idx'),
        ),
    ]
